### ISSUE TITLE
English documentation

### ISSUE THREAD

**Issue by BayramInanc** [iWECon/StackKit#15]
I will use it in production app. Can you provide english documentation?

**Comment by iwecon** [comment]
Aha, sure, but it may have to wait until the weekend. There have been a lot of things to do at work recently.

**Comment by BayramInanc** [comment]
One question can I use auto layout for the vstack, and hstack?

**Comment by iwecon** [comment]
Yes, support auto layout, the size of the view is calculated based on `view.sizeToFit()`.

<img width="1407" alt="CleanShot 2022-08-29 at 20 38 16@2x" src="https://user-images.githubusercontent.com/16604027/187203033-1294cf98-972f-45cc-8b34-46f79fd27ccc.png">

**Comment by BayramInanc** [comment]
Thank you great work!

**Comment by iwecon** [comment]
@BayramInanc I added Demo with some basic (H/VStackView) usage. #16 
More documentation needs to wait until the weekend.
